---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: kafdrop
  namespace: strimzi
  labels:
    strimzi.io/cluster: kafka
spec:
  authentication:
    type: scram-sha-512
  authorization:
    type: simple
    acls:
      # Allow reading from all topics
      - resource:
          type: topic
          name: "*"
        operations:
          - Read
          - Describe
      # Allow describing cluster (includes ACL descriptions)
      - resource:
          type: cluster
        operations:
          - Describe
          - DescribeConfigs
          - ClusterAction
      # Allow reading consumer group metadata
      - resource:
          type: group
          name: "*"
        operations:
          - Read
          - Describe
