---
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka
  namespace: strimzi
  labels:
    strimzi.io/cluster: kafka
spec:
  kafka:
    version: 4.1.0
    metadataVersion: 4.1-IV0
    authorization:
      type: simple
      superUsers:
        - CN=kafka
        - CN=kafka-client
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
        authentication:
          type: scram-sha-512
      - name: external
        port: 9094
        type: ingress
        tls: true
        authentication:
          type: scram-sha-512
        configuration:
          class: nginx
          hostTemplate: kafka-broker-{nodeId}.cryptoviz.epitech-msc2026.me
          bootstrap:
            host: kafka-bootstrap.cryptoviz.epitech-msc2026.me
    config:
      auto.create.topics.enable: "false"
      default.replication.factor: 3
      min.insync.replicas: 2
      log.retention.hours: 1
      log.segment.bytes: 1073741824 # 1 GB segments for better performance
      num.network.threads: 8
      num.io.threads: 8
      socket.send.buffer.bytes: 102400
      socket.receive.buffer.bytes: 102400
      socket.request.max.bytes: 104857600 # 100 MB
      group.initial.rebalance.delay.ms: 3000
      offsets.topic.replication.factor: 3
      offsets.topic.num.partitions: 50
      transaction.state.log.replication.factor: 3
      transaction.state.log.num.partitions: 50
  entityOperator:
    topicOperator:
      resources:
        requests:
          memory: 512Mi
          cpu: 250m
        limits:
          memory: 1Gi
          cpu: 500m
    userOperator:
      resources:
        requests:
          memory: 512Mi
          cpu: 250m
        limits:
          memory: 1Gi
          cpu: 500m
