---
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka
  namespace: kafka
  labels:
    strimzi.io/cluster: kafka
spec:
  kafka:
    version: 3.7.0
    metadataVersion: 3.7-IV0
    replicas: 3
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
        authentication:
          type: scram-sha-512
      - name: external
        port: 9094
        type: nodeport
        tls: true
        authentication:
          type: scram-sha-512
    config:
      auto.create.topics.enable: "false"
      default.replication.factor: 3
      min.insync.replicas: 2
      log.retention.hours: 1
      log.segment.bytes: 1073741824 # 1 GB segments for better performance
      num.network.threads: 8
      num.io.threads: 8
      socket.send.buffer.bytes: 102400
      socket.receive.buffer.bytes: 102400
      socket.request.max.bytes: 104857600 # 100 MB
      group.initial.rebalance.delay.ms: 3000
      offsets.topic.replication.factor: 3
      offsets.topic.num.partitions: 50
      transaction.state.log.replication.factor: 3
      transaction.state.log.num.partitions: 50
    brokerRackInitialization:
      enabled: true
  zookeeper:
    replicas: 3
    storage:
      type: persistent-claim
      size: 10Gi
    resources:
      requests:
        memory: 512Mi
        cpu: 250m
      limits:
        memory: 1Gi
        cpu: 500m
  entityOperator:
    topicOperator:
      resources:
        requests:
          memory: 512Mi
          cpu: 250m
        limits:
          memory: 1Gi
          cpu: 500m
    userOperator:
      resources:
        requests:
          memory: 512Mi
          cpu: 250m
        limits:
          memory: 1Gi
          cpu: 500m
  cruiseControl:
    brokerCapacity:
      inboundNetwork: 10000KB/s # 10 MB/s per broker
      outboundNetwork: 10000KB/s # 10 MB/s per broker
      disk: "300Gi"
    resources:
      requests:
        memory: 512Mi
        cpu: 250m
      limits:
        memory: 1Gi
        cpu: 1000m
    config:
      # Cruisecontrol config goes here
      num.concurrent.partition.movements.per.broker: 5
      num.concurrent.leader.movements: 1000
      default.goals: "com.linkedin.kafka.cruisecontrol.analyzer.goals.RackAwareGoal,com.linkedin.kafka.cruisecontrol.analyzer.goals.TopicReplicaDistributionGoal,com.linkedin.kafka.cruisecontrol.analyzer.goals.ReplicaCapacityGoal"
