apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app
  namespace: argocd
  # Ensure that all Kubernetes resources deployed by the application are properly
  # deleted before the Application itself is deleted.
  finalizers:
    - resources-finalizer.argocd.argoproj.io/finalizer
spec:
  project: default
  sources:
    # ArgoCD Projects to group related content
    - repoURL: https://github.com/T-DAT-901-MSC-2026-PAR-1/infrastructure
      targetRevision: main
      path: argocd/appprojects/
      directory:
        recurse: true
    # ArgoCD Applications
    - repoURL: https://github.com/T-DAT-901-MSC-2026-PAR-1/infrastructure
      targetRevision: main
      path: argocd/applications/
      directory:
        recurse: true
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true