---
# RBAC configuration for ArgoCD
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/part-of: argocd
data:
  # Default policy for authenticated users
  policy.default: role:readonly
  
  # CSV format for RBAC policies
  policy.csv: |
    # Admin access for T-DAT-901-MSC-2026-PAR-1 org members
    g, T-DAT-901-MSC-2026-PAR-1, role:admin

    # Read-only access for all authenticated users
    p, role:readonly, applications, get, */*, allow
    p, role:readonly, applicationsets, get, */*, allow
    p, role:readonly, clusters, get, *, allow
    p, role:readonly, repositories, get, *, allow
    p, role:readonly, projects, get, *, allow
    p, role:readonly, logs, get, */*, allow