---
# General Argo CD configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  # Argo CD's externally facing base URL (optional). Required when configuring SSO
  url: https://argocd.cryptoviz.epitech-msc2026.me
  # Enables application status badge feature
  statusbadge.enabled: "true"
  # Enable insecure mode for server (will be terminated by ingress)
  server.insecure: "true"
  # Application instance label key
  application.instanceLabelKey: argocd.argoproj.io/instance
  
  # Dex configuration for GitHub OAuth
  dex.config: |
    connectors:
    - type: github
      id: github
      name: GitHub
      config:
        baseURL: https://github.com
        clientID: $ARGOCD_DEX_GITHUB_CLIENT_ID
        clientSecret: $ARGOCD_DEX_GITHUB_CLIENT_SECRET
        redirectURI: https://argocd.cryptoviz.epitech-msc2026.me/api/dex/callback
        orgs:
        - name: T-DAT-901-MSC-2026-PAR-1
          # Allow all organization members access