---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: strimzi
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4" # Deployed after argocd-config
spec:
  project: default
  sources:
    - repoURL: https://strimzi.io/charts/
      chart: strimzi-kafka-operator
      targetRevision: 0.48.0
      helm:
        valuesObject:
          installCRDs: true

  destination:
    server: https://kubernetes.default.svc
    namespace: strimzi
  syncPolicy:
    automated:
      prune: true # Delete the resources that doesn't exists anymore in the git repository
      selfHeal: true # Correct manual edits done on the cluster
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true